import { app, BrowserWindow, ipcMain } from "electron";
import Store from "electron-store";
import installExtension, {
  REACT_DEVELOPER_TOOLS,
  REDUX_DEVTOOLS,
} from "electron-devtools-installer";
import { updateElectronApp } from "update-electron-app";
import { StoreType } from "./backend/core/typing";
import { LiveChat } from "./backend/core/yt/live-chat";
import { IPC } from "./shared/ipc-commands";
import { Mode } from "./shared/types";
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

const store = new Store<StoreType>({
  schema: {
    video: {
      type: "object",
      default: {
        id: "0",
      },
      properties: {
        id: {
          type: "string",
          default: "0",
        },
      },
      required: ["id"],
    },
    settings: {
      type: "object",
      default: {
        mode: "democracy",
      },
      properties: {
        mode: {
          type: "string",
          enum: ["democracy", "monarchy", "anarchy"],
          default: "democracy",
        },
        democracyCountdown: {
          type: "number",
          default: 5000,
        },
        monarchyCooldown: {
          type: "number",
          default: 15000,
        },
        normalInterval: {
          type: "number",
          default: 500,
        },
        username: {
          type: "string",
          default: "thmo_",
        },
      },
      required: ["mode"],
    },
  },
});

const chat = new LiveChat();

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

updateElectronApp();

const createWindow = (): BrowserWindow => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 575,
    width: 530,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
    // transparent: true,
    // frame: false,
    autoHideMenuBar: true,
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  // if (!app.isPackaged) mainWindow.webContents.openDevTools();

  return mainWindow;
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", async () => {
  const mainWindow = createWindow();

  ipcMain.handle(IPC.MAIN.REQUEST_INITIAL_DATA, (_) => {
    return {
      videoId: store.get("video.id"),
      mode: store.get("settings.mode"),
      democracyCountdown: store.get("settings.democracyCountdown"),
      monarchyCooldown: store.get("settings.monarchyCooldown"),
      normalInterval: store.get("settings.normalInterval"),
    };
  });

  ipcMain.on(IPC.MAIN.START, async (_) => {
    await chat.start(mainWindow, store.store);
  });

  ipcMain.on(IPC.MAIN.STOP, (_) => {
    chat.stop();
  });

  ipcMain.on(IPC.MAIN.SET_VIDEO_ID, (_, id: string) => {
    store.set("video.id", id);
    mainWindow.webContents.send(IPC.MAIN.VIDEO_ID_SET, store.get("video.id"));
  });

  ipcMain.on(IPC.MAIN.SET_MODE, (_, mode: Mode) => {
    store.set("settings.mode", mode);
    mainWindow.webContents.send(IPC.MAIN.MODE_SET, store.get("settings.mode"));
  });

  ipcMain.on(IPC.MAIN.SET_DEMOCRACY_COUNTDOWN, (_, value: number) => {
    store.set("settings.democracyCountdown", value);
    mainWindow.webContents.send(
      IPC.MAIN.DEMOCRACY_COUNTDOWN_SET,
      store.get("settings.democracyCountdown")
    );
  });

  ipcMain.on(IPC.MAIN.SET_MONARCHY_COOLDOWN, (_, value: number) => {
    store.set("settings.monarchyCooldown", value);
    mainWindow.webContents.send(
      IPC.MAIN.MONARCHY_COOLDOWN_SET,
      store.get("settings.monarchyCooldown")
    );
  });

  ipcMain.on(IPC.MAIN.SET_NORMAL_INTERVAL, (_, value: number) => {
    store.set("settings.normalInterval", value);
    mainWindow.webContents.send(
      IPC.MAIN.NORMAL_INTERVAL_SET,
      store.get("settings.normalInterval")
    );
  });
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    chat.exit();
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

app.whenReady().then(() => {
  installExtension([REDUX_DEVTOOLS, REACT_DEVELOPER_TOOLS])
    .then((name) => console.log(`[YTPlays] Added Extension:  ${name}`))
    .catch((err) => console.log("[YTPlays] An error occurred: ", err));
});
